version: "3.3"

networks:
  proxy-public:
    external: false

services:

  proxy:
    ports:
      - "{{cookiecutter.development_port}}:80"
    build:
      context: ./proxy
      dockerfile: proxy.dockerfile
    networks:
      - proxy-public
      - default
    depends_on:
      - backend
    deploy:
      placement:
        constraints:
          - node.role == manager

  db:
    image: postgres:14
    ports:
      - "1050:5432"
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    deploy:
      placement:
        constraints:
          - node.labels.nexly.app-db-data == true

  backend:
    depends_on:
      - db
    ports:
      - "1041:80"
    env_file:
      - .env
    environment:
      - SERVICE=backend
    volumes:
      - ./backend/app:/app
    build:
      context: ./backend
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
    command: /start-reload.sh

volumes:
  app-db-data:

